controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

live_chart:
    path: /chart
    controller: App\Controller\MainController::chart
